In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
def has_duplicates(x):
    return len(x) > len(x.unique())

def view_all_df(temp):
    with pd.option_context('display.max_rows', None, 'display.max_columns', None):
        display(temp)
        
def create_rename_dict_from_list_name_tuple(list_name_tuple):
    rename_dict = {}
    for l,n in list_name_tuple:
        for e in l:
            rename_dict[e]=n
    return rename_dict

## The other

In [4]:
rename_list = [
    (['Ladder score', 'Life Ladder'], 'Ladder score'),
    (['Log GDP per capita'], 'Logged GDP per capita'),
    (
 ['Healthy life expectancy at birth'],
 'Healthy life expectancy')
]

rename_dict = create_rename_dict_from_list_name_tuple(rename_list)

In [5]:
df = pd.read_csv('../data/2021.csv')#.rename(rename_dict, axis='columns')
df['rank'] = df.index+1
df.loc[:, 'year'] = 2021

temp = pd.read_csv(f'../data/2015_to_2020.csv').rename(rename_dict, axis='columns')

for year in range(2005, 2021):
    per_year = temp[temp['year']==year].sort_values(by=['Ladder score'], ascending=False).reset_index(drop=True)
    per_year['rank'] = per_year.index+1

    # Concatenating
    df = pd.concat([df, per_year], ignore_index=True)

In [6]:
main_cols = ['country', 'report_year', 'dystopia_residual', 'gdp_per_capita', 'happiness_rank', 'happiness_score', 'life_expectancy', 'trust', 'freedom', 'generosity', 'social_support']
view_all_df((df[df['Country name']=='United States']).loc[:, ['year', 'Healthy life expectancy']])

      year  Healthy life expectancy
18    2021                    68.20
180   2006                    68.06
267   2007                    68.22
376   2008                    68.38
484   2009                    68.54
604   2010                    68.70
727   2011                    68.68
877   2012                    68.66
1014  2013                    68.64
1151  2014                    68.62
1299  2015                    68.60
1448  2016                    68.50
1588  2017                    68.40
1736  2018                    68.30
1877  2019                    68.20
2016  2020                    68.10

In [7]:
sorted(df.columns)

['Country name',
 'Dystopia + residual',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Healthy life expectancy',
 'Explained by: Log GDP per capita',
 'Explained by: Perceptions of corruption',
 'Explained by: Social support',
 'Freedom to make life choices',
 'Generosity',
 'Healthy life expectancy',
 'Ladder score',
 'Ladder score in Dystopia',
 'Logged GDP per capita',
 'Negative affect',
 'Perceptions of corruption',
 'Positive affect',
 'Regional indicator',
 'Social support',
 'Standard error of ladder score',
 'lowerwhisker',
 'rank',
 'upperwhisker',
 'year']

In [8]:
df = df.sort_values(by=['Country name', 'year']).reset_index(drop=True)

In [9]:
df

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,rank,year,Positive affect,Negative affect
0,Afghanistan,NaN,3.724,NaN,NaN,NaN,7.370,0.451,50.800,0.718,...,NaN,NaN,NaN,NaN,NaN,NaN,105,2008,0.518,0.258
1,Afghanistan,NaN,4.402,NaN,NaN,NaN,7.540,0.552,51.200,0.679,...,NaN,NaN,NaN,NaN,NaN,NaN,96,2009,0.584,0.237
2,Afghanistan,NaN,4.758,NaN,NaN,NaN,7.647,0.539,51.600,0.600,...,NaN,NaN,NaN,NaN,NaN,NaN,84,2010,0.618,0.275
3,Afghanistan,NaN,3.832,NaN,NaN,NaN,7.620,0.521,51.920,0.496,...,NaN,NaN,NaN,NaN,NaN,NaN,140,2011,0.611,0.267
4,Afghanistan,NaN,3.783,NaN,NaN,NaN,7.705,0.521,52.240,0.531,...,NaN,NaN,NaN,NaN,NaN,NaN,136,2012,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,Zimbabwe,NaN,3.638,NaN,NaN,NaN,8.016,0.754,55.000,0.753,...,NaN,NaN,NaN,NaN,NaN,NaN,139,2017,0.806,0.224
2094,Zimbabwe,NaN,3.616,NaN,NaN,NaN,8.049,0.775,55.600,0.763,...,NaN,NaN,NaN,NaN,NaN,NaN,135,2018,0.710,0.212
2095,Zimbabwe,NaN,2.694,NaN,NaN,NaN,7.950,0.759,56.200,0.632,...,NaN,NaN,NaN,NaN,NaN,NaN,143,2019,0.716,0.235
2096,Zimbabwe,NaN,3.160,NaN,NaN,NaN,7.829,0.717,56.800,0.643,...,NaN,NaN,NaN,NaN,NaN,NaN,95,2020,0.703,0.346
2097,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.03,7.943,0.750,56.201,0.677,...,0.649,0.243,0.359,0.157,0.075,1.205,148,2021,NaN,NaN

In [10]:
df.to_csv('../data/final_data.csv', index=False)

<hr style="height:10px;">
<h1 style="color:red"> Ignore Below </h1>
<h1 style="color:red"> Ignore Below </h1>
<h1 style="color:red"> Ignore Below </h1>
<h1 style="color:red"> Ignore Below </h1>
<h1 style="color:red"> Ignore Below </h1>
<hr style="height:10px;">

## Read the final and see

In [11]:
temp = pd.read_csv('../data/final_data.csv')

In [12]:
temp

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,rank,year,Positive affect,Negative affect
0,Afghanistan,NaN,3.724,NaN,NaN,NaN,7.370,0.451,50.800,0.718,...,NaN,NaN,NaN,NaN,NaN,NaN,105,2008,0.518,0.258
1,Afghanistan,NaN,4.402,NaN,NaN,NaN,7.540,0.552,51.200,0.679,...,NaN,NaN,NaN,NaN,NaN,NaN,96,2009,0.584,0.237
2,Afghanistan,NaN,4.758,NaN,NaN,NaN,7.647,0.539,51.600,0.600,...,NaN,NaN,NaN,NaN,NaN,NaN,84,2010,0.618,0.275
3,Afghanistan,NaN,3.832,NaN,NaN,NaN,7.620,0.521,51.920,0.496,...,NaN,NaN,NaN,NaN,NaN,NaN,140,2011,0.611,0.267
4,Afghanistan,NaN,3.783,NaN,NaN,NaN,7.705,0.521,52.240,0.531,...,NaN,NaN,NaN,NaN,NaN,NaN,136,2012,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2093,Zimbabwe,NaN,3.638,NaN,NaN,NaN,8.016,0.754,55.000,0.753,...,NaN,NaN,NaN,NaN,NaN,NaN,139,2017,0.806,0.224
2094,Zimbabwe,NaN,3.616,NaN,NaN,NaN,8.049,0.775,55.600,0.763,...,NaN,NaN,NaN,NaN,NaN,NaN,135,2018,0.710,0.212
2095,Zimbabwe,NaN,2.694,NaN,NaN,NaN,7.950,0.759,56.200,0.632,...,NaN,NaN,NaN,NaN,NaN,NaN,143,2019,0.716,0.235
2096,Zimbabwe,NaN,3.160,NaN,NaN,NaN,7.829,0.717,56.800,0.643,...,NaN,NaN,NaN,NaN,NaN,NaN,95,2020,0.703,0.346
2097,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.03,7.943,0.750,56.201,0.677,...,0.649,0.243,0.359,0.157,0.075,1.205,148,2021,NaN,NaN

## Unofficial

### Preprocessing Done
- Renames
- Assume order in 2021 data implies rank

In [13]:
# Unofficial
rename_list = [(['Country name',
 'Country or region', 'Country'], 'country'),
(['Dystopia + residual',
 'Dystopia Residual',
 'Dystopia.Residual',
  'Dystopia Residual'], 'dystopia_residual'),
(['Economy (GDP per Capita)',
 'Economy..GDP.per.Capita.',
 'GDP per capita'], 'gdp_per_capita'),
(['Happiness.Rank', 'Happiness Rank', 'Overall rank'], 'happiness_rank'),
(['Happiness.Score', 'Happiness Score', 'Score', 'Ladder score'], 'happiness_score'),
(['Health (Life Expectancy)',
 'Health..Life.Expectancy.',
 'Healthy life expectancy',], 'life_expectancy'),
# (['Ladder score in Dystopia'], 'Ladder score'),
(['Trust..Government.Corruption.'], 'trust'),
(['Whisker.high'], 'upperwhisker'),
(['Whisker.low'], 'lowerwhisker'),

               ([
 'Freedom',
 'Freedom to make life choices',], 'freedom'),
               (['Generosity'], 'generosity'),
               (['Social support'], 'social_support')
]

rename_dict = create_rename_dict_from_list_name_tuple(rename_list)

In [14]:
df = pd.read_csv('../data/2021.csv').rename(rename_dict, axis='columns')
df['happiness_rank'] = df.index+1
df.loc[:, 'report_year'] = 2021

for year in range(2015, 2021):
    temp = pd.read_csv(f'../data/{year}.csv').rename(rename_dict, axis='columns')
    
    # If 2020 add rank
    if year==2020:
        temp['happiness_rank'] = temp.index+1
    
    # Concatenating
    temp.loc[:, 'report_year'] = year
    df = pd.concat([df, temp], ignore_index=True)
    
    # Printing some subset of columns
    show_cols = ['report_year']
    for s in ['Log GDP per capita', 'Logged GDP per capita', 'Year', 'year']:
        if s in df.columns:
            show_cols.append(s)
    #     view_all_df(df[df['country']=='United States'].loc[:, show_cols])
    
# df = df.sort_values(by=['country', 'report_year']).reset_index(drop=True)

In [15]:
sorted(df.columns)

['Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Healthy life expectancy',
 'Explained by: Log GDP per capita',
 'Explained by: Perceptions of corruption',
 'Explained by: Social support',
 'Family',
 'Ladder score in Dystopia',
 'Logged GDP per capita',
 'Lower Confidence Interval',
 'Perceptions of corruption',
 'Region',
 'Regional indicator',
 'Standard Error',
 'Standard error of ladder score',
 'Trust (Government Corruption)',
 'Upper Confidence Interval',
 'country',
 'dystopia_residual',
 'freedom',
 'gdp_per_capita',
 'generosity',
 'happiness_rank',
 'happiness_score',
 'life_expectancy',
 'lowerwhisker',
 'report_year',
 'social_support',
 'trust',
 'upperwhisker']

In [16]:
main_cols = ['country', 'report_year', 'dystopia_residual', 'gdp_per_capita', 'happiness_rank', 'happiness_score', 'life_expectancy', 'trust', 'freedom', 'generosity', 'social_support']
view_all_df((df[df['country']=='United States']).loc[:, ['Logged GDP per capita', 'gdp_per_capita']])

     Logged GDP per capita  gdp_per_capita
18               11.023000             NaN
163                    NaN        1.394510
319                    NaN        1.507960
477                    NaN        1.546259
636                    NaN        1.398000
793                    NaN        1.433000
948              10.925769             NaN

## Official

In [17]:
# Official
rename_list=[
(['WP5 Country', 'Country name'], 'country')
]
rename_dict = create_rename_dict_from_list_name_tuple(rename_list)

In [18]:
df = pd.read_csv('../data/official/2015.csv')

In [19]:
df

,WP5 Country,country,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,...,Confidence in national government,Democratic Quality,Delivery Quality,"Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014"
0,070 Afghanistan,Afghanistan,2008,3.723590,7.178332,0.450662,47.862461,0.718114,0.179613,0.881686,...,0.612072,-1.962724,-1.665895,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,070 Afghanistan,Afghanistan,2009,4.401778,7.344422,0.552308,48.275078,0.678896,0.201416,0.850035,...,0.611545,-2.082451,-1.647938,0.286315,NaN,NaN,NaN,NaN,NaN,NaN
2,070 Afghanistan,Afghanistan,2010,4.758381,7.400804,0.539075,48.673412,0.600127,0.135185,0.706766,...,0.299357,-2.015701,-1.630097,0.275833,NaN,NaN,NaN,NaN,NaN,NaN
3,070 Afghanistan,Afghanistan,2011,3.831719,7.435526,0.521104,49.053383,0.495901,0.172412,0.731109,...,0.307386,-1.947305,-1.620275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,070 Afghanistan,Afghanistan,2012,3.782938,7.545960,0.520637,49.415783,0.530935,0.243653,0.775620,...,0.435440,-1.868366,-1.434265,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,081 Zimbabwe,Zimbabwe,2010,4.681570,7.302658,0.856638,45.276947,0.664718,-0.064795,0.828361,...,0.471201,-1.299463,-1.666921,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1107,081 Zimbabwe,Zimbabwe,2011,4.845642,7.393823,0.864694,47.264912,0.632978,-0.058497,0.829800,...,0.425926,-1.211812,-1.612017,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1108,081 Zimbabwe,Zimbabwe,2012,4.955101,7.418631,0.896476,49.038841,0.469531,-0.065246,0.858691,...,0.407084,-1.115116,-1.482212,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1109,081 Zimbabwe,Zimbabwe,2013,4.690188,7.406036,0.799274,50.812775,0.575884,-0.065734,0.830937,...,0.527755,NaN,NaN,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942
1110,081 Zimbabwe,Zimbabwe,2014,4.184451,7.395250,0.765839,52.586704,0.642034,-0.034259,0.820217,...,0.566209,NaN,NaN,NaN,NaN,NaN,NaN,0.116683,NaN,0.082942

In [20]:
df = pd.read_csv('../data/official/2021.csv').rename(rename_dict)
df.loc[:, 'report_year'] = 2021

for year in range(2015, 2021):
    temp = pd.read_csv(f'../data/official/{year}.csv').rename(rename_dict)
    temp.loc[:, 'report_year'] = year
    df = pd.concat([df, temp], ignore_index=True)
    
    # Printing some subset of columns
    show_cols = ['report_year']
    for s in ['Log GDP per capita', 'Logged GDP per capita', 'Year', 'year']:
        if s in df.columns:
            show_cols.append(s)
    view_all_df(df[df['country']=='United States'].loc[:, show_cols])
    
df = df.sort_values(by=['country', 'report_year']).reset_index(drop=True)
df

      report_year  Log GDP per capita  Logged GDP per capita    year
1195         2015           10.830686                    NaN  2006.0
1196         2015           10.838916                    NaN  2007.0
1197         2015           10.826550                    NaN  2008.0
1198         2015           10.789359                    NaN  2009.0
1199         2015           10.805829                    NaN  2010.0
1200         2015           10.816864                    NaN  2011.0
1201         2015           10.836948                    NaN  2012.0
1202         2015           10.848380                    NaN  2013.0
1203         2015           10.867021                    NaN  2014.0

      report_year  Log GDP per capita  Logged GDP per capita    year
1195         2015           10.830686                    NaN  2006.0
1196         2015           10.838916                    NaN  2007.0
1197         2015           10.826550                    NaN  2008.0
1198         2015           10.789359                    NaN  2009.0
1199         2015           10.805829                    NaN  2010.0
1200         2015           10.816864                    NaN  2011.0
1201         2015           10.836948                    NaN  2012.0
1202         2015           10.848380                    NaN  2013.0
1203         2015           10.867021                    NaN  2014.0
2459         2016           10.831686                    NaN  2006.0
2460         2016           10.839805                    NaN  2007.0
2461         2016           10.827426                    NaN  2008.0
2462         2016           10.790511                    NaN  2009.0
2463         2016           10.807155                    NaN  2010.0
2464         2016           10.815396                    NaN  2011.0
2465         2016           10.830702                    NaN  2012.0
2466         2016           10.845087                    NaN  2013.0
2467         2016           10.861260                    NaN  2014.0
2468         2016           10.877965                    NaN  2015.0

      report_year  Log GDP per capita  Logged GDP per capita    year
1195         2015           10.830686                    NaN  2006.0
1196         2015           10.838916                    NaN  2007.0
1197         2015           10.826550                    NaN  2008.0
1198         2015           10.789359                    NaN  2009.0
1199         2015           10.805829                    NaN  2010.0
1200         2015           10.816864                    NaN  2011.0
1201         2015           10.836948                    NaN  2012.0
1202         2015           10.848380                    NaN  2013.0
1203         2015           10.867021                    NaN  2014.0
2459         2016           10.831686                    NaN  2006.0
2460         2016           10.839805                    NaN  2007.0
2461         2016           10.827426                    NaN  2008.0
2462         2016           10.790511                    NaN  2009.0
2463         2016           10.807155                    NaN  2010.0
2464         2016           10.815396                    NaN  2011.0
2465         2016           10.830702                    NaN  2012.0
2466         2016           10.845087                    NaN  2013.0
2467         2016           10.861260                    NaN  2014.0
2468         2016           10.877965                    NaN  2015.0
3870         2017           10.831686                    NaN  2006.0
3871         2017           10.839805                    NaN  2007.0
3872         2017           10.827426                    NaN  2008.0
3873         2017           10.790511                    NaN  2009.0
3874         2017           10.807156                    NaN  2010.0
3875         2017           10.815405                    NaN  2011.0
3876         2017           10.829783                    NaN  2012.0
3877         2017           10.837194                    NaN  2013.0
3878         2017           10.853375                    NaN  2014.0
3879         2017           10.869501                    NaN  2015.0
3880         2017           10.879706                    NaN  2016.0

      report_year  Log GDP per capita  Logged GDP per capita    year
1195         2015           10.830686                    NaN  2006.0
1196         2015           10.838916                    NaN  2007.0
1197         2015           10.826550                    NaN  2008.0
1198         2015           10.789359                    NaN  2009.0
1199         2015           10.805829                    NaN  2010.0
1200         2015           10.816864                    NaN  2011.0
1201         2015           10.836948                    NaN  2012.0
1202         2015           10.848380                    NaN  2013.0
1203         2015           10.867021                    NaN  2014.0
2459         2016           10.831686                    NaN  2006.0
2460         2016           10.839805                    NaN  2007.0
2461         2016           10.827426                    NaN  2008.0
2462         2016           10.790511                    NaN  2009.0
2463         2016           10.807155                    NaN  2010.0
2464         2016           10.815396                    NaN  2011.0
2465         2016           10.830702                    NaN  2012.0
2466         2016           10.845087                    NaN  2013.0
2467         2016           10.861260                    NaN  2014.0
2468         2016           10.877965                    NaN  2015.0
3870         2017           10.831686                    NaN  2006.0
3871         2017           10.839805                    NaN  2007.0
3872         2017           10.827426                    NaN  2008.0
3873         2017           10.790511                    NaN  2009.0
3874         2017           10.807156                    NaN  2010.0
3875         2017           10.815405                    NaN  2011.0
3876         2017           10.829783                    NaN  2012.0
3877         2017           10.837194                    NaN  2013.0
3878         2017           10.853375                    NaN  2014.0
3879         2017           10.869501                    NaN  2015.0
3880         2017           10.879706                    NaN  2016.0
5425         2018           10.831686                    NaN  2006.0
5426         2018           10.839805                    NaN  2007.0
5427         2018           10.827426                    NaN  2008.0
5428         2018           10.790511                    NaN  2009.0
5429         2018           10.807152                    NaN  2010.0
5430         2018           10.815583                    NaN  2011.0
5431         2018           10.830115                    NaN  2012.0
5432         2018           10.839746                    NaN  2013.0
5433         2018           10.855743                    NaN  2014.0
5434         2018           10.876660                    NaN  2015.0
5435         2018           10.884476                    NaN  2016.0
5436         2018           10.899869                    NaN  2017.0

      report_year  Log GDP per capita  Logged GDP per capita  Year    year
1195         2015           10.830686                    NaN   NaN  2006.0
1196         2015           10.838916                    NaN   NaN  2007.0
1197         2015           10.826550                    NaN   NaN  2008.0
1198         2015           10.789359                    NaN   NaN  2009.0
1199         2015           10.805829                    NaN   NaN  2010.0
1200         2015           10.816864                    NaN   NaN  2011.0
1201         2015           10.836948                    NaN   NaN  2012.0
1202         2015           10.848380                    NaN   NaN  2013.0
1203         2015           10.867021                    NaN   NaN  2014.0
2459         2016           10.831686                    NaN   NaN  2006.0
2460         2016           10.839805                    NaN   NaN  2007.0
2461         2016           10.827426                    NaN   NaN  2008.0
2462         2016           10.790511                    NaN   NaN  2009.0
2463         2016           10.807155                    NaN   NaN  2010.0
2464         2016           10.815396                    NaN   NaN  2011.0
2465         2016           10.830702                    NaN   NaN  2012.0
2466         2016           10.845087                    NaN   NaN  2013.0
2467         2016           10.861260                    NaN   NaN  2014.0
2468         2016           10.877965                    NaN   NaN  2015.0
3870         2017           10.831686                    NaN   NaN  2006.0
3871         2017           10.839805                    NaN   NaN  2007.0
3872         2017           10.827426                    NaN   NaN  2008.0
3873         2017           10.790511                    NaN   NaN  2009.0
3874         2017           10.807156                    NaN   NaN  2010.0
3875         2017           10.815405                    NaN   NaN  2011.0
3876         2017           10.829783                    NaN   NaN  2012.0
3877         2017           10.837194                    NaN   NaN  2013.0
3878         2017           10.853375                    NaN   NaN  2014.0
3879         2017           10.869501                    NaN   NaN  2015.0
3880         2017           10.879706                    NaN   NaN  2016.0
5425         2018           10.831686                    NaN   NaN  2006.0
5426         2018           10.839805                    NaN   NaN  2007.0
5427         2018           10.827426                    NaN   NaN  2008.0
5428         2018           10.790511                    NaN   NaN  2009.0
5429         2018           10.807152                    NaN   NaN  2010.0
5430         2018           10.815583                    NaN   NaN  2011.0
5431         2018           10.830115                    NaN   NaN  2012.0
5432         2018           10.839746                    NaN   NaN  2013.0
5433         2018           10.855743                    NaN   NaN  2014.0
5434         2018           10.876660                    NaN   NaN  2015.0
5435         2018           10.884476                    NaN   NaN  2016.0
5436         2018           10.899869                    NaN   NaN  2017.0

      report_year  Log GDP per capita  Logged GDP per capita  Year    year
1195         2015           10.830686                    NaN   NaN  2006.0
1196         2015           10.838916                    NaN   NaN  2007.0
1197         2015           10.826550                    NaN   NaN  2008.0
1198         2015           10.789359                    NaN   NaN  2009.0
1199         2015           10.805829                    NaN   NaN  2010.0
1200         2015           10.816864                    NaN   NaN  2011.0
1201         2015           10.836948                    NaN   NaN  2012.0
1202         2015           10.848380                    NaN   NaN  2013.0
1203         2015           10.867021                    NaN   NaN  2014.0
2459         2016           10.831686                    NaN   NaN  2006.0
2460         2016           10.839805                    NaN   NaN  2007.0
2461         2016           10.827426                    NaN   NaN  2008.0
2462         2016           10.790511                    NaN   NaN  2009.0
2463         2016           10.807155                    NaN   NaN  2010.0
2464         2016           10.815396                    NaN   NaN  2011.0
2465         2016           10.830702                    NaN   NaN  2012.0
2466         2016           10.845087                    NaN   NaN  2013.0
2467         2016           10.861260                    NaN   NaN  2014.0
2468         2016           10.877965                    NaN   NaN  2015.0
3870         2017           10.831686                    NaN   NaN  2006.0
3871         2017           10.839805                    NaN   NaN  2007.0
3872         2017           10.827426                    NaN   NaN  2008.0
3873         2017           10.790511                    NaN   NaN  2009.0
3874         2017           10.807156                    NaN   NaN  2010.0
3875         2017           10.815405                    NaN   NaN  2011.0
3876         2017           10.829783                    NaN   NaN  2012.0
3877         2017           10.837194                    NaN   NaN  2013.0
3878         2017           10.853375                    NaN   NaN  2014.0
3879         2017           10.869501                    NaN   NaN  2015.0
3880         2017           10.879706                    NaN   NaN  2016.0
5425         2018           10.831686                    NaN   NaN  2006.0
5426         2018           10.839805                    NaN   NaN  2007.0
5427         2018           10.827426                    NaN   NaN  2008.0
5428         2018           10.790511                    NaN   NaN  2009.0
5429         2018           10.807152                    NaN   NaN  2010.0
5430         2018           10.815583                    NaN   NaN  2011.0
5431         2018           10.830115                    NaN   NaN  2012.0
5432         2018           10.839746                    NaN   NaN  2013.0
5433         2018           10.855743                    NaN   NaN  2014.0
5434         2018           10.876660                    NaN   NaN  2015.0
5435         2018           10.884476                    NaN   NaN  2016.0
5436         2018           10.899869                    NaN   NaN  2017.0

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,"Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-13","gini of household income reported in Gallup, by wp5-year","GINI index (World Bank estimate), average 2000-15",Year,"GINI index (World Bank estimate), average 2000-16"
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.450662,NaN,0.718114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.552308,NaN,0.678896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.539075,NaN,0.600127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.521104,NaN,0.495901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.520637,NaN,0.530935,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7368,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787000,48.700,0.715000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7369,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784000,59.269,0.824000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7370,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552000,61.400,0.897000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7371,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750000,56.201,0.677000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7372,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463000,52.493,0.382000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
sorted(df.columns)

['Confidence in national government',
 'Country name',
 'Delivery Quality',
 'Democratic Quality',
 'Dystopia + residual',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Healthy life expectancy',
 'Explained by: Log GDP per capita',
 'Explained by: Perceptions of corruption',
 'Explained by: Social support',
 'Freedom to make life choices',
 'GINI index (World Bank estimate)',
 'GINI index (World Bank estimate), average 2000-13',
 'GINI index (World Bank estimate), average 2000-15',
 'GINI index (World Bank estimate), average 2000-16',
 'Generosity',
 'Healthy life expectancy',
 'Healthy life expectancy at birth',
 'Ladder score',
 'Ladder score in Dystopia',
 'Life Ladder',
 'Log GDP per capita',
 'Logged GDP per capita',
 'Most people can be trusted, Gallup',
 'Most people can be trusted, WVS round 1981-1984',
 'Most people can be trusted, WVS round 1989-1993',
 'Most people can be trusted, WVS round 1994-1998',
 'Most people can be trusted, WVS round 1999-2004',
 'Most people can be trusted, WVS round 2005-2009',
 'Most people can be trusted, WVS round 2010-2014',
 'Negative affect',
 'Perceptions of corruption',
 'Positive affect',
 'Regional indicator',
 'Social support',
 'Standard deviation of ladder by country-year',
 'Standard deviation/Mean of ladder by country-year',
 'Standard error of ladder score',
 'WP5 Country',
 'Year',
 'country',
 'gini of household income reported in Gallup, by wp5-year',
 'lowerwhisker',
 'report_year',
 'upperwhisker',
 'year']

In [22]:
df[df['Country name']=='United States'].shape

(15, 47)

In [23]:
view_all_df(df[df['Country name']=='United States'])

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,report_year,WP5 Country,country,year,Life Ladder,Log GDP per capita,Healthy life expectancy at birth,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,"Most people can be trusted, Gallup","Most people can be trusted, WVS round 1981-1984","Most people can be trusted, WVS round 1989-1993","Most people can be trusted, WVS round 1994-1998","Most people can be trusted, WVS round 1999-2004","Most people can be trusted, WVS round 2005-2009","Most people can be trusted, WVS round 2010-2014",Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-13","gini of household income reported in Gallup, by wp5-year","GINI index (World Bank estimate), average 2000-15",Year,"GINI index (World Bank estimate), average 2000-16"
6971,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.964572,NaN,0.911496,NaN,0.600309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.181794,10.831686,68.059998,0.827417,0.260511,0.558029,0.797783,1.546490,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.873673,0.260892,NaN,NaN,NaN,NaN,2006.0,0.408167
6972,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.871904,0.188272,0.633035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.512688,10.839805,68.220001,0.828503,0.231679,0.393245,0.742770,1.539012,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.723988,0.229477,0.411,NaN,NaN,NaN,2007.0,0.408167
6973,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.952587,NaN,0.877956,0.246029,0.668495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.280386,10.827426,68.379997,0.871968,0.226823,0.379221,0.864745,1.559145,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.778600,0.244300,NaN,NaN,NaN,NaN,2008.0,0.408167
6974,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.911794,NaN,0.830684,0.192269,0.665394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.158032,10.790511,68.540001,0.843484,0.261661,0.503047,0.772818,1.450143,0.370746,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,2.021277,0.282379,NaN,NaN,0.705702,NaN,2009.0,0.408167
6975,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.926159,NaN,0.828044,0.235522,0.689583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.163616,10.807183,68.699997,0.860642,0.231053,0.418276,0.786005,1.478330,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,2.182074,0.304605,0.404,NaN,0.739406,NaN,2010.0,0.408167
6976,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.921705,NaN,0.863202,0.152239,0.696926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.115139,10.815644,68.680000,0.836360,0.273379,0.382532,0.859107,1.462401,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.945976,0.273498,NaN,NaN,0.612990,NaN,2011.0,0.408167
6977,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.903192,NaN,0.822662,0.206243,0.710034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.026227,10.830132,68.660004,0.833771,0.259644,0.348856,0.897015,1.467070,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,2.163160,0.307869,NaN,NaN,0.629069,NaN,2012.0,0.408167
6978,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.925397,NaN,0.792256,0.265563,0.746894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.249285,10.839653,68.639999,0.813678,0.260328,0.288648,0.873046,1.415544,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.938088,0.267349,0.410,NaN,0.678262,NaN,2013.0,0.408167
6979,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.902097,NaN,0.866077,0.212869,0.702267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,7.151114,10.857497,68.620003,0.834294,0.281265,0.348671,0.826821,1.433888,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,2.070654,0.289557,NaN,NaN,0.753396,NaN,2014.0,0.408167
6980,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.903571,NaN,0.848753,0.210956,0.697543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,6.863947,10.878154,68.599998,0.813908,0.274688,0.346936,0.893903,1.428245,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.953670,0.284628,NaN,NaN,0.649792,NaN,2015.0,0.408167
6981,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.896751,NaN,0.757893,0.135592,0.738920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,6.803600,10.885554,68.500000,0.805674,0.264204,0.297206,0.755765,1.491426,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.972203,0.289876,0.415,NaN,0.693315,NaN,2016.0,0.408167
6982,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.921003,NaN,0.868497,0.188833,0.681191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,6.991759,10.900906,68.400002,0.826555,0.268269,0.386535,0.677056,1.552135,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,1.880688,0.268986,NaN,NaN,0.610804,NaN,2017.0,0.408167
6983,United States,NaN,NaN,NaN,NaN,NaN,NaN,0.903856,NaN,0.824607,0.107713,0.709928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,NaN,NaN,NaN,6.882685,10.922465,68.300003,0.815383,0.292226,0.313816,NaN,NaN,NaN,0.453548,NaN,0.349513,0.355185,0.393451,0.351395,2.119374,0.307928,NaN,NaN,0.701418,NaN,2018.0,0.408167
7088,United States,North America and ANZ,6.9396,0.047316,7.03234,6.84686,10.925769,0.914219,68.2995,0.842620,0.149892,0.699715,1.972317,1.373987,1.404787,0.831618,0.534608,0.298143,0.152285,2.344125,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7242,United States,North America and ANZ,6.9510,0.049000,7.04700,6.85600,11.023000,0.920000,68.2000,0.837000,0.098000,0.698000,2.430000,1.533000,1.030000,0.621000,0.554000,0.252000,0.154000,2.807000,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN